# kubectl apply -f configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
data:
  SPLUNK_TRACE_URL: "https://ingest.us1.signalfx.com/v2/trace"
  SPLUNK_API_URL: "https://api.us1.signalfx.com"
  SPLUNK_INGEST_URL: "https://ingest.us1.signalfx.com"
  SPLUNK_HEC_URL: "https://<your host>:8088/services/collector"
  CLOUDWATCH_LOG_GROUP_NAME: "<log group name>"
  CLOUDWATCH_LOG_STREAM_NAME: "<log stream name>"
  CLOUDWATCH_REGION: "us-west-1"
