mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
  hostMetrics:
    enabled: true

extraEnvs:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: otel-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: otel-secret
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_SESSION_TOKEN
    valueFrom:
      secretKeyRef:
        name: otel-secret
        key: AWS_SESSION_TOKEN
  - name: SPLUNK_HEC_TOKEN
    valueFrom:
      secretKeyRef:
        name: otel-secret
        key: SPLUNK_HEC_TOKEN
  - name: SPLUNK_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: otel-secret
        key: SPLUNK_ACCESS_TOKEN
  - name: SPLUNK_TRACE_URL
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: SPLUNK_TRACE_URL
  - name: SPLUNK_API_URL
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: SPLUNK_API_URL
  - name: SPLUNK_INGEST_URL
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: SPLUNK_INGEST_URL
  - name: SPLUNK_HEC_URL
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: SPLUNK_HEC_URL
  - name: CLOUDWATCH_LOG_GROUP_NAME
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: CLOUDWATCH_LOG_GROUP_NAME
  - name: CLOUDWATCH_LOG_STREAM_NAME
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: CLOUDWATCH_LOG_STREAM_NAME
  - name: CLOUDWATCH_REGION
    valueFrom:
      configMapKeyRef:
        name: otel-configmap
        key: CLOUDWATCH_REGION

config:
  processors:
    resourcedetection:
      detectors: [ ec2, eks ]
      override: true
  exporters:
    splunk_hec:
      token: "${SPLUNK_HEC_TOKEN}"
      endpoint: "${SPLUNK_HEC_URL}"
      profiling_data_enabled: false
    awscloudwatchlogs:
      log_group_name: "${CLOUDWATCH_LOG_GROUP_NAME}"
      log_stream_name: "${CLOUDWATCH_LOG_STREAM_NAME}"
      region: "${CLOUDWATCH_REGION}"
    # Traces
    sapm:
      access_token: "${SPLUNK_ACCESS_TOKEN}"
      endpoint: "${SPLUNK_TRACE_URL}"
    # Metrics + Events
    signalfx:
      access_token: "${SPLUNK_ACCESS_TOKEN}"
      api_url: "${SPLUNK_API_URL}"
      ingest_url: "${SPLUNK_INGEST_URL}"
      sync_host_metadata: true
  service:
    pipelines:
      traces:
        processors: [resourcedetection]
        exporters: [sapm, signalfx]
      metrics:
        processors: [resourcedetection]
        exporters: [signalfx]
      logs:
        processors: [resourcedetection]
        exporters: [splunk_hec, awscloudwatchlogs]